version: '3'
services:
  database:
    build: ./services/database
    ports:
      - '5432:5432'
  scraper:
    build: ./services/scraper
    depends_on:
      - database
    volumes:
      - ./services/scraper/:/scraper
    environment:
      NODE_ENV: development
      LUMINATI_PROXY_IP: zproxy.lum-superproxy.io:22225
      LUMINATI_USERNAME: lum-customer-hl_db37e9dc-zone-static_res
      LUMINATI_PASSWORD: x4qtoz19csah
      PORT: 6000
      API_PORT: 5000
  api:
    build: ./services/api
    depends_on:
      - database
    ports:
      - '5000:5000'
    volumes:
      - ./services/api/:/api
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_USER: docker
      DB_PASSWORD: docker
      DB_NAME: docker
      DB_URL: database
      DB_PORT: 5432
